from .base_class import Base
from .amizade import Amizade
from .classe import Classe
from .skill import Skill
from .status import Status
from .user import User
from .exercicio import Exercicio
from .campeonato import Campeonato
from .exercicio import Exercicio
from .rotina import Rotina
from .grupo_muscular import GrupoMuscular
from .treino import Treino
from .exercicio_campeonato import ExercicioCampeonato
from .exercicio_rotina import ExercicioRotina
from .item import Item
from .user_skill import user_skill
from .user_exercicio import UserExercicio