"""nome e tipo na tabela treino

Revision ID: 23b6c154a4c7
Revises: b31daf35e3e7
Create Date: 2024-10-30 16:42:03.428834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b6c154a4c7'
down_revision: Union[str, None] = 'b31daf35e3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treino', sa.Column('nome', sa.String(), nullable=False))
    vals, name = ("rotina", "campeonato"), "tipotreino"
    sa_enum = sa.Enum(*vals, name=name)
    sa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('treino', sa.Column('tipo', sa_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treino', 'nome')
    op.drop_column('treino', 'tipo')
    # ### end Alembic commands ###
