"""peso, altura e status

Revision ID: 5f680d46c15e
Revises: 9597fbb64ccc
Create Date: 2024-11-23 16:00:15.875507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5f680d46c15e'
down_revision: Union[str, None] = '9597fbb64ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('peso', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('altura', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'altura')
    op.drop_column('user', 'peso')
    # ### end Alembic commands ###
