"""latlon em campeonato

Revision ID: 745e5f41ce44
Revises: 7b5137b978d0
Create Date: 2025-04-15 15:18:50.716086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '745e5f41ce44'
down_revision: Union[str, None] = '7b5137b978d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonato', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('campeonato', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campeonato', 'longitude')
    op.drop_column('campeonato', 'latitude')
    # ### end Alembic commands ###
