"""rename userexercicio to treinoexercicio, coluna foto em treino

Revision ID: 7b5137b978d0
Revises: dba64b25e620
Create Date: 2025-04-03 14:53:54.419988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b5137b978d0'
down_revision: Union[str, None] = 'dba64b25e620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treino_exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('exec_rotina_id', sa.Integer(), nullable=True),
    sa.Column('exec_campeonato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exec_campeonato_id'], ['exercicio_campeonato.id'], ),
    sa.ForeignKeyConstraint(['exec_rotina_id'], ['exercicio_rotina.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_exercicio')
    op.add_column('treino', sa.Column('imagem', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treino', 'imagem')
    op.create_table('user_exercicio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('treino_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exec_rotina_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exec_campeonato_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exec_campeonato_id'], ['exercicio_campeonato.id'], name='user_exercicio_exec_campeonato_id_fkey'),
    sa.ForeignKeyConstraint(['exec_rotina_id'], ['exercicio_rotina.id'], name='user_exercicio_exec_rotina_id_fkey'),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], name='user_exercicio_treino_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_exercicio_pkey')
    )
    op.drop_table('treino_exercicio')
    # ### end Alembic commands ###
