"""criado por em campeonato

Revision ID: 9597fbb64ccc
Revises: 23b6c154a4c7
Create Date: 2024-11-04 14:57:05.074615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9597fbb64ccc'
down_revision: Union[str, None] = '23b6c154a4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonato', sa.Column('data_criacao', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.add_column('campeonato', sa.Column('criado_por_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'campeonato', 'user', ['criado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campeonato', type_='foreignkey')
    op.drop_column('campeonato', 'criado_por_id')
    op.drop_column('campeonato', 'data_criacao')
    # ### end Alembic commands ###
