"""status treino

Revision ID: 9b653ad898dd
Revises: 5f680d46c15e
Create Date: 2024-12-05 13:43:21.708169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b653ad898dd'
down_revision: Union[str, None] = '5f680d46c15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vals, name = ("ativo", "deletado"), "statustreino"
    sa_enum = sa.Enum(*vals, name=name)
    sa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('treino', sa.Column('status', sa_enum, nullable=False, server_default="ativo"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treino', 'status')
    # ### end Alembic commands ###
