"""name

Revision ID: b31daf35e3e7
Revises: eaa1b8d32c40
Create Date: 2024-10-30 16:17:59.213721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31daf35e3e7'
down_revision: Union[str, None] = 'eaa1b8d32c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercicio_campeonato', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercicio_rotina', 'rotina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercicio_rotina', 'rotina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercicio_campeonato', 'campeonato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
