"""pontos em exec campeonato

Revision ID: cdd1732d8ccc
Revises: 9b653ad898dd
Create Date: 2025-03-28 16:44:23.108932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdd1732d8ccc'
down_revision: Union[str, None] = '9b653ad898dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicio_campeonato', sa.Column('pontos', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicio_campeonato', 'pontos')
    # ### end Alembic commands ###
