"""delete classe and skill

Revision ID: dba64b25e620
Revises: cdd1732d8ccc
Create Date: 2025-03-29 10:55:53.128820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dba64b25e620'
down_revision: Union[str, None] = 'cdd1732d8ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill', if_exists=True)
    op.drop_table('user_skill', if_exists=True)
    op.drop_table('classe', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='classe_pkey')
    )
    op.create_table('user_skill',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='user_skill_skill_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_skill_user_id_fkey')
    )
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_pkey')
    )
    # ### end Alembic commands ###
